### ISSUE TITLE
Possible contributions for functions not implemented yet?

### ISSUE THREAD

**Issue by MartinMorlot** [hzambran/hydroGOF#15]
Hi Prof. Zambrano,

I am currently doing my PhD in Trento and I am using your library quite often, as part of my work, I am having to implement several functions not found in hydroGOF.

Would you accept a contribution? The ones I am thinking about are, MAPE, Bias Ratio, variability ratio.

I would just be happy to be listed as a contributor here, no need to add me on the citation or anything.

Let me know if this is ok with you.

**Comment by hzambran** [comment]
Hi Martin,

Thank you very much for your message. 

Of course I would accept contributions with functions not implemented yet.

I'm not very familiar with pull request yet, but you might try to suggest a pull request and then I would accept it (with or without modifications), with your name as the developer of that particular function, and as a contributor of the package. Please try to follow the rationale of existing functions (e.g., KGE), regarding construction of the functions, documentation, and avoid the use of other external packages, which create dependency problems that I wan to avoid as much as possible.

If the pull request does not work (because of my limited time), please e-mail me to mauricio.zambrano @ ufrontera.cl would be another (less desirable) way to make it.

_Saluti a UniTN !_
