### ISSUE TITLE
NSE equals R2?

### ISSUE THREAD

**Issue by gpf75ks** [hzambran/hydroGOF#24]
Just upgraded to v0.8 (same issue with 0.5) and notice that calculated NSE is equal R2, can't be possible unless a perfect model (sim=obs). NSE = 1- MSE/Var(obs), R2 = SSres/SSTot

I've used the simple example and verified too with the EgaEnEstellaQts data
obs <- 1:100
sim <- obs
sim <- 100:1
gof(sim,obs)

**Comment by hzambran** [comment]
The problem is not with the NSE or the R2 functions, but with the gof and ggof functions.

The issue was raised by the several new GoFs included in the newest CRAN version 0.5-3. See the discussion here: https://github.com/hzambran/hydroGOF/issues/23#issuecomment-2017789250.


Thank you very much @seyounger for your detailed example.

The issue was raised by the several new GoFs included in the newest CRAN version 0.5-3.

The new version 0.5-14 (only in github yet) has solved this issue. Please test it and report any problem. This new version should be submitted to CRAN in the next few days.
