### ISSUE TITLE
error in calculating bR2

### ISSUE THREAD

**Issue by whiteellie** [hzambran/hydroGOF#9]
line 49 in br2.R file should read: 

br2 <- ifelse(**abs(b)** <= 1, r2*abs(b), r2/abs(b))

**Comment by hzambran** [comment]
Strictly speaking, there is no error in the implementation of `br2` in `hydroGOF`, because its implementation is based on equation (5) in:

> Krause, P., Boyle, D. P., & Bäse, F. (2005). Comparison of different efficiency criteria for hydrological model assessment. SRef-ID: 1680-7359/adgeo/2005-5-89. https://www.adv-geosci.net/5/89/2005/adgeo-5-89-2005.pdf

which uses `b` and not `abs(b)`

However, to ensure that equation (5) makes sense, the condition to discriminate the formula to be applied should be `abs(b)`.

So far nobody has reported  this point because if  `b` is negative it means that your simulations have nothing to do with your observations, which should not be the case.

I'm updating the package now (pushed by comments from CRAN about compatibility with the upcoming new version of R), and I will include an argument `use.abs` to allow the user to use `abs(b)` as discriminant.
